language: none

build:
    pre_ci:
        - apt-get install -y dos2unix
        - image=${REPO_NAME##*-}
        - docker build -t justin8/$image .
        - version=$(docker run justin8/$image cat /version | dos2unix)
        - docker tag justin8/$image:latest justin8/$image:$version
        - docker images
    push:
        - echo "Pushing justin8/$image:$version"
        - docker push justin8/$image:$version
        - docker push justin8/$image:latest

integrations:
    hub:
        - integrationName: dockerhub
          type: docker
